- id: checkstyle
  name: checkstyle
  description: "Runs the Checkstyle static code analysis tool."
  language: script #coursier language doesn't support changing jvm version. Checkstyle doesn't work on java 8
  entry: ./checkstyle
  files: \.java$
  require_serial: true
