#!/usr/bin/env bash
set -euo pipefail

cs="$(${BASH_SOURCE%/*}/resolve_coursier)"
$cs launch \
  --jvm=zulu:1.17 \
  -M com.puppycrawl.tools.checkstyle.Main \
  com.puppycrawl.tools:checkstyle:10.6.0 -- "$@"
